stages:
   - buildAndDeploy
dev:  
   image: node:12.16.1
     
   stage: buildAndDeploy 
   script:
      - git reset --hard
      - export PATH=$PATH:/usr/bin/npm    
      - yarn install   
      - CI=false yarn run build:dev
      - pip3 install awscli
      - chmod +x ~/.local/bin/aws
      - aws s3 sync ./build s3://bril-okr
   rules:
      - if: ($CI_COMMIT_BRANCH == "Developer")     
   artifacts:    
      paths:      
         - build/    
      expire_in: 1 hour
   tags:
    - brilcrm
prod:  
   image: node:12.16.1
     
   stage: buildAndDeploy 
   script:
      - git reset --hard
      - export PATH=$PATH:/usr/bin/npm    
      - yarn install   
      - CI=false yarn run build:prod
      - pip3 install awscli
      - chmod +x ~/.local/bin/aws
      - aws s3 sync ./build s3://prod-bril-okr
   rules:
      - if: ($CI_COMMIT_BRANCH == "master")     
   artifacts:    
      paths:      
         - build/    
      expire_in: 1 hour
   tags:
    - brilcrm    